#tw_statuses_public_timeline:
#  class: sfRequestRoute
#  url: /tw/statuses/public_timeline.:sf_format
#  param: { module: twStatuses, action: publicTimeline }
#  requirements: { sf_method: [get], sf_format: "^(json|xml)$" }

tw_statuses_home_timeline:
  class: sfRequestRoute
  url: /tw/statuses/home_timeline.:sf_format
  param: { module: twStatuses, action: homeTimeline }
  requirements: { sf_method: [get], sf_format: "^(json|xml)$" }

tw_statuses_friends_timeline:
  class: sfRequestRoute
  url: /tw/statuses/friends_timeline.:sf_format
  param: { module: twStatuses, action: homeTimeline }
  requirements: { sf_method: [get], sf_format: "^(json|xml)$" }

tw_statuses_update:
  class: sfRequestRoute
  url: /tw/statuses/update.:sf_format
  param: { module: twStatuses, action: update }
  requirements: { sf_method: [post], sf_format: "^(json|xml)$" }

tw_statuses_deny:
  class: sfRoute
  url: /twStatues/*
  param: { module: twApi, action: error404 }

tw_account_verify_credentials:
  class: sfRequestRoute
  url: /tw/account/verify_credentials.:sf_format
  param: { module: twAccount, action: verifyCredentials }
  requirements: { sf_method: [get], sf_format: "^(json|xml)$" }

tw_account_deny:
  class: sfRoute
  url: /twAccount/*
  param: { module: twApi, action: error404 }

